export const BROKER_CONNECTION_CATALOG = [
  {
    providerId: "mt5",
    provider: "MT5 / MetaTrader 5",
    coverage: "CFD, futures, matieres premieres, forex, actions",
    mode: "bridge-direct",
    detail: "Connexion directe deja supportee par le bridge MT5 TXT.",
  },
  {
    providerId: "prime-broker",
    provider: "Prime / CFD broker",
    coverage: "Indices, commodities, forex, single stocks",
    mode: "adapter-request",
    detail: "Onboarding via adaptateur broker dedie ou FIX/OpenAPI si disponible.",
  },
  {
    providerId: "prop-platform",
    provider: "Prop firm desktop / web terminal",
    coverage: "Prop futures, CFD, forex",
    mode: "platform-adapter",
    detail: "Preferer un adaptateur natif plateforme; ne pas supposer MT5 si la firme utilise son propre terminal.",
  },
] as const;

export const EXCHANGE_CONNECTION_CATALOG = [
  {
    providerId: "binance",
    provider: "Binance",
    coverage: "Spot, margin, futures, subaccounts",
    mode: "api-key",
    detail: "Cle API segregee lecture/trading avec gestion des sous-comptes et transferts internes.",
  },
  {
    providerId: "bitget",
    provider: "Bitget",
    coverage: "Spot, perp, copy, broker API",
    mode: "api-key",
    detail: "Cle API + secret + permissions lecture/trading segmentees.",
  },
  {
    providerId: "bingx",
    provider: "BingX",
    coverage: "Spot, futures",
    mode: "api-key",
    detail: "Integration par cle API si disponible; sinon onboarding adaptateur specifique.",
  },
  {
    providerId: "kraken",
    provider: "Kraken",
    coverage: "Spot, margin, futures",
    mode: "api-key",
    detail: "Connexion API key ou OAuth selon la politique de compte client.",
  },
  {
    providerId: "okx",
    provider: "OKX",
    coverage: "Spot, margin, futures, options",
    mode: "api-key",
    detail: "TXT peut router execution et market-data via connecteur exchange dedie.",
  },
  {
    providerId: "coinbase",
    provider: "Coinbase",
    coverage: "Spot, advanced trade, custody",
    mode: "api-key",
    detail: "Connexion pour trading ou supervision custody suivant les permissions.",
  },
  {
    providerId: "bybit",
    provider: "Bybit",
    coverage: "Spot, perp, options",
    mode: "api-key",
    detail: "Connexion par cle API si le client opere principalement sur produits derives.",
  },
  {
    providerId: "kucoin",
    provider: "KuCoin",
    coverage: "Spot, margin, futures",
    mode: "api-key",
    detail: "Parcours API key avec passphrase et droits separes lecture/trade.",
  },
  {
    providerId: "mexc",
    provider: "MEXC",
    coverage: "Spot, futures",
    mode: "api-key",
    detail: "Connexion API key pour environnement CEX retail ou prop crypto.",
  },
  {
    providerId: "gateio",
    provider: "Gate.io",
    coverage: "Spot, perp, earn",
    mode: "api-key",
    detail: "Cle API segregee avec mode read ou trade.",
  },
  {
    providerId: "hyperliquid",
    provider: "Hyperliquid",
    coverage: "Perp DEX",
    mode: "wallet-signing",
    detail: "Connexion wallet + signature; execution via adaptateur DEX faible latence.",
  },
  {
    providerId: "dydx",
    provider: "dYdX",
    coverage: "Perp DEX",
    mode: "wallet-signing",
    detail: "Connexion via wallet signing et flux DEX dedie.",
  },
  {
    providerId: "polymarket",
    provider: "Polymarket",
    coverage: "Prediction markets",
    mode: "wallet-signing",
    detail: "Connexion wallet / custody pour marche evenementiel et prediction.",
  },
  {
    providerId: "pumpfun",
    provider: "Pump.fun / Aster",
    coverage: "Launch / on-chain venue",
    mode: "wallet-signing",
    detail: "Acces via wallet et endpoint on-chain dedie, pas via bridge MT5.",
  },
] as const;

export const WALLET_CONNECTION_CATALOG = [
  {
    providerId: "metamask",
    provider: "MetaMask",
    coverage: "EVM wallets, signing, DEX connectivity",
    mode: "walletconnect",
    detail: "Connexion browser wallet pour EVM, settlement et signature.",
  },
  {
    providerId: "rabby",
    provider: "Rabby",
    coverage: "EVM wallets, DeFi, multi-chain execution",
    mode: "walletconnect",
    detail: "Wallet EVM expert avec verification de chain et simulation de transaction.",
  },
  {
    providerId: "coinbase-wallet",
    provider: "Coinbase Wallet",
    coverage: "EVM wallet, retail custody, DeFi",
    mode: "walletconnect",
    detail: "Connexion wallet retail pour execution ou simple supervision on-chain.",
  },
  {
    providerId: "safe",
    provider: "Safe / Gnosis Safe",
    coverage: "Treasury multisig, custody, execution controls",
    mode: "safe-api",
    detail: "Connexion treasury multisig pour reserve, custody et execution gouvernee.",
  },
  {
    providerId: "fireblocks",
    provider: "Fireblocks",
    coverage: "Institutional custody, treasury, transfers",
    mode: "custody-api",
    detail: "Connexion custody institutionnelle pour verification des avoirs et mouvements gouvernes.",
  },
  {
    providerId: "ledger",
    provider: "Ledger",
    coverage: "BTC, ETH, SOL, custody hardware",
    mode: "watch-only-or-signing",
    detail: "Hardware wallet pour reserve, watch-only ou signing assiste.",
  },
  {
    providerId: "trezor",
    provider: "Trezor",
    coverage: "BTC, ETH, custody hardware",
    mode: "watch-only-or-signing",
    detail: "Hardware wallet pour custody froide ou verification d'adresse.",
  },
  {
    providerId: "btc-wallet",
    provider: "BTC wallet",
    coverage: "BTC custody / settlement",
    mode: "watch-only-or-signing",
    detail: "Mode watch-only ou signing selon la politique de garde.",
  },
  {
    providerId: "solana-wallet",
    provider: "Solana wallet",
    coverage: "SOL ecosystem, on-chain venues",
    mode: "walletconnect",
    detail: "Connexion par adresse/wallet adapter pour venues Solana.",
  },
  {
    providerId: "phantom",
    provider: "Phantom",
    coverage: "SOL ecosystem, Jupiter, on-chain execution",
    mode: "walletconnect",
    detail: "Wallet Solana pour execution on-chain, Jupiter et routing ecosysteme SOL.",
  },
  {
    providerId: "evm-wallet",
    provider: "ETH wallet",
    coverage: "EVM settlement, DeFi, DEX",
    mode: "walletconnect",
    detail: "Connexion wallet ou custody API pour execution et controle de solde.",
  },
  {
    providerId: "walletconnect",
    provider: "WalletConnect generic",
    coverage: "EVM multi-wallet, mobile signing",
    mode: "walletconnect",
    detail: "Point d'entree generique pour connecter un wallet mobile via WalletConnect.",
  },
] as const;

export type ConnectionProviderType = "broker" | "exchange" | "wallet" | "prop";